services:
  db:
    image: postgis/postgis:13-3.1
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mapdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./server
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: mapdata
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./client
    ports:
      - "3000:3000"
    depends_on:
      - backend

  scraper:
    build:
      context: ./scraper
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: mapdata
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: